version: '3'

services:
  db:
    image: postgres:11.9
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  web:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      /bin/sh -c
        'echo "Waiting for postgres..." &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo "PostgreSQL started" &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080'
    links:
      - redis
